.PHONY: clean All

All:
	@echo "----------Building project:[ FizzBuzz - Debug ]----------"
	@cd "FizzBuzz" && "$(MAKE)" -f  "FizzBuzz.mk"
clean:
	@echo "----------Cleaning project:[ FizzBuzz - Debug ]----------"
	@cd "FizzBuzz" && "$(MAKE)" -f  "FizzBuzz.mk" clean
